/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _qinwei_dsh_server_manager_serverManager_addServer_parameter_0$schema = z.object({
  'host': z.string(),
  'id': z.union([z.undefined(), z.string()]).optional(),
  'name': z.union([z.undefined(), z.string()]).optional(),
  'role': z.union([z.undefined(), z.string()]).optional(),
  'sshUser': z.union([z.undefined(), z.string()]).optional(),
  'sshPort': z.union([z.undefined(), z.number()]).optional(),
  'bmcHost': z.union([z.undefined(), z.string()]).optional(),
  'bmcUser': z.union([z.undefined(), z.string()]).optional(),
  'bmcPassword': z.union([z.undefined(), z.string()]).optional(),
  'tags': z.union([z.undefined(), z.string()]).optional(),
  'notes': z.union([z.undefined(), z.string()]).optional(),
})
const _qinwei_dsh_server_manager_serverManager_addServer_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
  'server': z.object({
  'id': z.string(),
  'name': z.string(),
  'role': z.string(),
  'host': z.string(),
  'sshUser': z.string(),
  'sshPort': z.number(),
  'bmcHost': z.string(),
  'bmcUser': z.string(),
  'bmcPassword': z.string(),
  'tags': z.array(z.string()),
  'notes': z.string(),
  'enabled': z.boolean(),
  'createdAt': z.number(),
  'updatedAt': z.number(),
}),
})])
const _qinwei_dsh_server_manager_serverManager_bmcBios_parameter_0$schema = z.object({
  'id': z.string(),
  'attribute': z.union([z.undefined(), z.string()]).optional(),
  'value': z.union([z.undefined(), z.string()]).optional(),
})
const _qinwei_dsh_server_manager_serverManager_bmcBios_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'attributeRegistry': z.union([z.literal(null), z.string()]),
  'attributeCount': z.number(),
  'attributes': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true)])),
}), z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'attribute': z.string(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true)]),
}), z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'set': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true)])),
  'note': z.string(),
}), z.object({
  'ok': z.literal(false),
  'error': z.string(),
  'transport': z.union([z.undefined(), z.string()]).optional(),
  'hint': z.union([z.undefined(), z.string()]).optional(),
})])
const _qinwei_dsh_server_manager_serverManager_bmcPower_parameter_0$schema = z.object({
  'id': z.string(),
  'action': z.string(),
})
const _qinwei_dsh_server_manager_serverManager_bmcPower_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'powerState': z.union([z.literal(null), z.string()]),
  'health': z.union([z.literal(null), z.string()]),
}), z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'requested': z.string(),
  'note': z.string(),
}), z.object({
  'ok': z.literal(false),
  'error': z.string(),
  'transport': z.union([z.undefined(), z.string()]).optional(),
})])
const _qinwei_dsh_server_manager_serverManager_bmcStatus_parameter_0$schema = z.object({
  'id': z.string(),
})
const _qinwei_dsh_server_manager_serverManager_bmcStatus_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'transport': z.string(),
  'model': z.union([z.literal(null), z.string()]),
  'manufacturer': z.union([z.literal(null), z.string()]),
  'serial': z.union([z.literal(null), z.string()]),
  'powerState': z.union([z.literal(null), z.string()]),
  'health': z.union([z.literal(null), z.string()]),
  'severity': z.union([z.literal(null), z.string()]),
}), z.object({
  'ok': z.literal(false),
  'error': z.string(),
  'transport': z.union([z.undefined(), z.string()]).optional(),
})])
const _qinwei_dsh_server_manager_serverManager_deleteServer_parameter_0$schema = z.object({
  'id': z.string(),
})
const _qinwei_dsh_server_manager_serverManager_deleteServer_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
})])
const _qinwei_dsh_server_manager_serverManager_exec_parameter_0$schema = z.object({
  'id': z.string(),
  'command': z.string(),
  'timeoutMs': z.union([z.undefined(), z.number()]).optional(),
})
const _qinwei_dsh_server_manager_serverManager_exec_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
  'results': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'host': z.string(),
  'ok': z.boolean(),
  'exitCode': z.union([z.literal(null), z.number()]),
  'stdout': z.string(),
  'stderr': z.string(),
  'error': z.union([z.literal(null), z.string()]),
  'timedOut': z.boolean(),
})),
})])
const _qinwei_dsh_server_manager_serverManager_inspect_parameter_0$schema = z.object({
  'id': z.union([z.undefined(), z.string()]).optional(),
})
const _qinwei_dsh_server_manager_serverManager_inspect_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
  'checkedAt': z.number(),
  'results': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'host': z.string(),
  'online': z.boolean(),
  'checkedAt': z.number(),
  'metrics': z.record(z.string(), z.string()),
  'error': z.union([z.literal(null), z.string()]),
})),
})])
const _qinwei_dsh_server_manager_serverManager_listServers_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
  'servers': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'role': z.string(),
  'host': z.string(),
  'sshUser': z.string(),
  'sshPort': z.number(),
  'bmcHost': z.string(),
  'bmcUser': z.string(),
  'bmcPassword': z.string(),
  'tags': z.array(z.string()),
  'notes': z.string(),
  'enabled': z.boolean(),
  'createdAt': z.number(),
  'updatedAt': z.number(),
})),
  'checks': z.record(z.string(), z.object({
  'id': z.string(),
  'name': z.string(),
  'host': z.string(),
  'online': z.boolean(),
  'checkedAt': z.number(),
  'metrics': z.record(z.string(), z.string()),
  'error': z.union([z.literal(null), z.string()]),
})),
  'lastInspectAt': z.union([z.literal(null), z.number()]),
  'inspectIntervalMs': z.number(),
  'hasIpmitool': z.boolean(),
  'bmcTransport': z.string(),
  'running': z.boolean(),
})])
const _qinwei_dsh_server_manager_serverManager_update_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'changed': z.boolean(),
  'beforeHash': z.union([z.literal(null), z.string()]),
  'afterHash': z.union([z.literal(null), z.string()]),
  'log': z.string(),
  'pullOutput': z.string(),
  'repoPath': z.string(),
  'note': z.string(),
}), z.object({
  'ok': z.literal(false),
  'error': z.string(),
})])
const _qinwei_dsh_server_manager_serverManager_updateServer_parameter_0$schema = z.object({
  'id': z.string(),
  'patch': z.object({
  'name': z.union([z.undefined(), z.string()]).optional(),
  'role': z.union([z.undefined(), z.string()]).optional(),
  'host': z.union([z.undefined(), z.string()]).optional(),
  'sshUser': z.union([z.undefined(), z.string()]).optional(),
  'sshPort': z.union([z.undefined(), z.number()]).optional(),
  'bmcHost': z.union([z.undefined(), z.string()]).optional(),
  'bmcUser': z.union([z.undefined(), z.string()]).optional(),
  'bmcPassword': z.union([z.undefined(), z.string()]).optional(),
  'tags': z.union([z.undefined(), z.string()]).optional(),
  'notes': z.union([z.undefined(), z.string()]).optional(),
  'enabled': z.union([z.undefined(), z.literal(false), z.literal(true)]).optional(),
}),
})
const _qinwei_dsh_server_manager_serverManager_updateServer_result$schema = z.union([z.object({
  'ok': z.literal(false),
  'error': z.string(),
}), z.object({
  'ok': z.literal(true),
  'server': z.object({
  'id': z.string(),
  'name': z.string(),
  'role': z.string(),
  'host': z.string(),
  'sshUser': z.string(),
  'sshPort': z.number(),
  'bmcHost': z.string(),
  'bmcUser': z.string(),
  'bmcPassword': z.string(),
  'tags': z.array(z.string()),
  'notes': z.string(),
  'enabled': z.boolean(),
  'createdAt': z.number(),
  'updatedAt': z.number(),
}),
})])

export const TYPERT = {
  package: '@qinwei/dsh-server-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@qinwei/dsh-server-manager#serverManager/addServer',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'addServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#AddServerRequest',
            schema: _qinwei_dsh_server_manager_serverManager_addServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#AddServerResult',
        schema: _qinwei_dsh_server_manager_serverManager_addServer_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":306,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/bmcBios',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'bmcBios',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#BmcBiosRequest',
            schema: _qinwei_dsh_server_manager_serverManager_bmcBios_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#BmcBiosResult',
        schema: _qinwei_dsh_server_manager_serverManager_bmcBios_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":394,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/bmcPower',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'bmcPower',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#BmcPowerRequest',
            schema: _qinwei_dsh_server_manager_serverManager_bmcPower_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#BmcPowerResult',
        schema: _qinwei_dsh_server_manager_serverManager_bmcPower_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":373,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/bmcStatus',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'bmcStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#IdRequest',
            schema: _qinwei_dsh_server_manager_serverManager_bmcStatus_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#BmcStatusResult',
        schema: _qinwei_dsh_server_manager_serverManager_bmcStatus_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":357,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/deleteServer',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'deleteServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#IdRequest',
            schema: _qinwei_dsh_server_manager_serverManager_deleteServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#DeleteServerResult',
        schema: _qinwei_dsh_server_manager_serverManager_deleteServer_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":328,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/exec',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'exec',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#ExecRequest',
            schema: _qinwei_dsh_server_manager_serverManager_exec_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#ExecResult',
        schema: _qinwei_dsh_server_manager_serverManager_exec_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":345,"column":9},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/inspect',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'inspect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#InspectRequest',
            schema: _qinwei_dsh_server_manager_serverManager_inspect_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#InspectResult',
        schema: _qinwei_dsh_server_manager_serverManager_inspect_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":339,"column":3},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/listServers',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'listServers',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#ListServersResult',
        schema: _qinwei_dsh_server_manager_serverManager_listServers_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":297,"column":3},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/update',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#UpdateResult',
        schema: _qinwei_dsh_server_manager_serverManager_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":427,"column":3},
    },
    {
      id: '@qinwei/dsh-server-manager#serverManager/updateServer',
      service: 'serverManager',
      namespace: 'serverManager',
      method: 'updateServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@qinwei/dsh-server-manager/types#UpdateServerRequest',
            schema: _qinwei_dsh_server_manager_serverManager_updateServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@qinwei/dsh-server-manager/types#UpdateServerResult',
        schema: _qinwei_dsh_server_manager_serverManager_updateServer_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-server-manager/src/index.ts","line":317,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
