/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AddServerRequest, AddServerResult, BmcBiosRequest, BmcBiosResult, BmcPowerRequest, BmcPowerResult, BmcStatusResult, DeleteServerResult, ExecRequest, ExecResult, IdRequest, InspectRequest, InspectResult, ListServersResult, UpdateResult, UpdateServerRequest, UpdateServerResult } from '@qinwei/dsh-server-manager/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7365727665724d616e61676572 {
    addServer: (request: AddServerRequest) => Promise<RemoteResult<AddServerResult>>
    bmcBios: (request: BmcBiosRequest) => Promise<RemoteResult<BmcBiosResult>>
    bmcPower: (request: BmcPowerRequest) => Promise<RemoteResult<BmcPowerResult>>
    bmcStatus: (request: IdRequest) => Promise<RemoteResult<BmcStatusResult>>
    deleteServer: (request: IdRequest) => Promise<RemoteResult<DeleteServerResult>>
    exec: (request: ExecRequest) => Promise<RemoteResult<ExecResult>>
    inspect: (request: InspectRequest) => Promise<RemoteResult<InspectResult>>
    listServers: () => Promise<RemoteResult<ListServersResult>>
    update: () => Promise<RemoteResult<UpdateResult>>
    updateServer: (request: UpdateServerRequest) => Promise<RemoteResult<UpdateServerResult>>
  }
  interface TypertRemoteMap {
    'serverManager/addServer': (request: AddServerRequest) => Promise<RemoteResult<AddServerResult>>
    'serverManager/bmcBios': (request: BmcBiosRequest) => Promise<RemoteResult<BmcBiosResult>>
    'serverManager/bmcPower': (request: BmcPowerRequest) => Promise<RemoteResult<BmcPowerResult>>
    'serverManager/bmcStatus': (request: IdRequest) => Promise<RemoteResult<BmcStatusResult>>
    'serverManager/deleteServer': (request: IdRequest) => Promise<RemoteResult<DeleteServerResult>>
    'serverManager/exec': (request: ExecRequest) => Promise<RemoteResult<ExecResult>>
    'serverManager/inspect': (request: InspectRequest) => Promise<RemoteResult<InspectResult>>
    'serverManager/listServers': () => Promise<RemoteResult<ListServersResult>>
    'serverManager/update': () => Promise<RemoteResult<UpdateResult>>
    'serverManager/updateServer': (request: UpdateServerRequest) => Promise<RemoteResult<UpdateServerResult>>
  }
  interface TypertRemoteNamespaceMap {
    'serverManager': TypertRemoteNamespace$7365727665724d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
