/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { BrowsePathRequest, BrowsePathResult, CancelTaskRequest, CancelTaskResult, CreateTaskRequest, CreateTaskResult, DeleteImageRequest, DeleteImageResult, DeleteTaskRequest, DeleteTaskResult, ExtractImageRequest, ExtractImageResult, GetConfigResult, GetServerListResult, GetTaskDetailRequest, GetTaskDetailResult, ListComponentsRequest, ListComponentsResult, ListImagesResult, ListTasksResult, ProbeDeviceRequest, ProbeDeviceResult, RegisterIsoRequest, RegisterIsoResult, ServiceControlResult, ServiceStatusResult, SetConfigRequest, SetConfigResult } from '@qinwei/dsh-os-deploy/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6f734465706c6f79 {
    browsePath: (req: BrowsePathRequest) => Promise<RemoteResult<BrowsePathResult>>
    cancelTask: (req: CancelTaskRequest) => Promise<RemoteResult<CancelTaskResult>>
    createTask: (req: CreateTaskRequest) => Promise<RemoteResult<CreateTaskResult>>
    deleteImage: (req: DeleteImageRequest) => Promise<RemoteResult<DeleteImageResult>>
    deleteTask: (req: DeleteTaskRequest) => Promise<RemoteResult<DeleteTaskResult>>
    extractImage: (req: ExtractImageRequest) => Promise<RemoteResult<ExtractImageResult>>
    getConfig: () => Promise<RemoteResult<GetConfigResult>>
    getTaskDetail: (req: GetTaskDetailRequest) => Promise<RemoteResult<GetTaskDetailResult>>
    listComponents: (req: ListComponentsRequest) => Promise<RemoteResult<ListComponentsResult>>
    listImages: () => Promise<RemoteResult<ListImagesResult>>
    listServers: () => Promise<RemoteResult<GetServerListResult>>
    listTasks: () => Promise<RemoteResult<ListTasksResult>>
    probeDevice: (req: ProbeDeviceRequest) => Promise<RemoteResult<ProbeDeviceResult>>
    registerIso: (req: RegisterIsoRequest) => Promise<RemoteResult<RegisterIsoResult>>
    serviceRestart: () => Promise<RemoteResult<ServiceControlResult>>
    serviceStart: () => Promise<RemoteResult<ServiceControlResult>>
    serviceStatus: () => Promise<RemoteResult<ServiceStatusResult>>
    serviceStop: () => Promise<RemoteResult<ServiceControlResult>>
    setConfig: (req: SetConfigRequest) => Promise<RemoteResult<SetConfigResult>>
  }
  interface TypertRemoteMap {
    'osDeploy/browsePath': (req: BrowsePathRequest) => Promise<RemoteResult<BrowsePathResult>>
    'osDeploy/cancelTask': (req: CancelTaskRequest) => Promise<RemoteResult<CancelTaskResult>>
    'osDeploy/createTask': (req: CreateTaskRequest) => Promise<RemoteResult<CreateTaskResult>>
    'osDeploy/deleteImage': (req: DeleteImageRequest) => Promise<RemoteResult<DeleteImageResult>>
    'osDeploy/deleteTask': (req: DeleteTaskRequest) => Promise<RemoteResult<DeleteTaskResult>>
    'osDeploy/extractImage': (req: ExtractImageRequest) => Promise<RemoteResult<ExtractImageResult>>
    'osDeploy/getConfig': () => Promise<RemoteResult<GetConfigResult>>
    'osDeploy/getTaskDetail': (req: GetTaskDetailRequest) => Promise<RemoteResult<GetTaskDetailResult>>
    'osDeploy/listComponents': (req: ListComponentsRequest) => Promise<RemoteResult<ListComponentsResult>>
    'osDeploy/listImages': () => Promise<RemoteResult<ListImagesResult>>
    'osDeploy/listServers': () => Promise<RemoteResult<GetServerListResult>>
    'osDeploy/listTasks': () => Promise<RemoteResult<ListTasksResult>>
    'osDeploy/probeDevice': (req: ProbeDeviceRequest) => Promise<RemoteResult<ProbeDeviceResult>>
    'osDeploy/registerIso': (req: RegisterIsoRequest) => Promise<RemoteResult<RegisterIsoResult>>
    'osDeploy/serviceRestart': () => Promise<RemoteResult<ServiceControlResult>>
    'osDeploy/serviceStart': () => Promise<RemoteResult<ServiceControlResult>>
    'osDeploy/serviceStatus': () => Promise<RemoteResult<ServiceStatusResult>>
    'osDeploy/serviceStop': () => Promise<RemoteResult<ServiceControlResult>>
    'osDeploy/setConfig': (req: SetConfigRequest) => Promise<RemoteResult<SetConfigResult>>
  }
  interface TypertRemoteNamespaceMap {
    'osDeploy': TypertRemoteNamespace$6f734465706c6f79
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
